In [4]:
import pandas as pd
import os


def findlines(filename):
    s_starts=[]
    t_starts=[]
    with open(filename) as file:
        for linenum, linetxt in enumerate(file,1):
            if "Study phase started at" in linetxt:
                s_starts.append(linenum)
            elif "Test phase started at" in linetxt:
                t_starts.append(linenum)
    return (s_starts, t_starts)


fname='MSTlog_010_Rest_pre.txt'
fname_final=fname[:-4]
fname_final=fname_final + ".csv"
s_starts,t_starts=findlines(fname)
n_stim_per=64
study_len = n_stim_per*2
test_len = n_stim_per*3


study_data=pd.read_csv(fname,sep='\t',skiprows=s_starts[0],header=0,nrows=study_len)
test_data=pd.read_csv(fname,sep='\t',skiprows=t_starts[0],header=0,nrows=test_len, skipinitialspace=True)

#Write to CSV if you want
#test_data.to_csv(fname_final)

# Restrict dataframe to Lures that were answered correctly
#test_data_filter=test_data[test_data['Acc'] == 1]
#test_data_filter=test_data_filter[test_data['Cond'] == "L"]

In [3]:
test_data
#test_data_filter
#means=test_data_filter.mean(0,1)
#means
#mean_RT=means[1,5]
#test_data

     Trial   Img Cond  LBin  Resp  Acc    RT
0        1  100b    L     4     1    0  3220
1        2  098a    F     0     3    1  1179
2        3  092b    L     4     1    0   988
3        4  048b    L     2     1    0  1945
4        5  173a    F     0     3    1   815
..     ...   ...  ...   ...   ...  ...   ...
187    188  065a    T     0     1    1   859
188    189  123a    F     0     3    1  1353
189    190  131b    L     5     1    0  1528
190    191  114a    T     0     1    1  1235
191    192  043b    L     5     1    0   968

[192 rows x 7 columns]